trigger: none

pr: none

variables:
- template: variables/pipeline-vars.yml
- name: devEnvironment
  value: dev


# resources:
#   pipelines:
#   - pipeline: CI
#     # TODO: Update with the name of your CI pipeline
#     source: ''
#     trigger:
#       branches:
#       - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          
          #  - task: DownloadPipelineArtifact@2
          #    inputs:
          #      artifact: 'logicAppCIArtifact'
          #      path: '$(Build.ArtifactStagingDirectory)'
          #  - script: dir
          #    workingDirectory: $(Build.ArtifactStagingDirectory)
          #    displayName: List contents of a folder

           - task: AzureCLI@2
             displayName: 'Deploy Logic App Workflows'
             inputs:
               azureSubscription: 'LAStandard' 
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
                 az logicapp deployment source config-zip \
                    --resource-group $(resourceGroupName) \
                    --name $(logicAppName) \
                    --src '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'